name: 'Visual Studio Marketplace Publisher'
description:
  'Publish your Visual Studio extensions to the marketplace with ease!'
author: 'Coding With Calvin'
branding:
  color: purple
  icon: upload-cloud
inputs:
  marketplace-pat:
    required: true
    description: 'Your personal access token for the Marketplace'
  publish-manifest-path:
    required: true
    description: 'Relative path to your publish manifest'
  vsix-path:
    required: true
    description: 'Relative path to your VSIX file'
  vs-version:
    description:
      'Version of Visual Studio to search; defaults to latest if not specified'
    required: false
  vs-prerelease:
    description: 'Enable searching for pre-release versions of Visual Studio'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
